export const CHANGE_COLUMNS_DATA = 'staffReport/change_columns_data'
export const CHANGE_STAFF_DATA = 'staffReport/change_staff_data'
export const ADD_STAFF_DATA = 'staffReport/add_staff_data'
export const DELETE_STAFF_DATA = 'staffReport/delete_staff_data'
export const UPDATE_STAFF_DATA = 'staffReport/update_staff_data'